# -----------------------------------------------------------------------------
# Example values for configuration of the CIVIDASH Civitas Dashboard addon's Helm file,
# replace this file with a proper configuration matching the Helm file's
# documentation
# -----------------------------------------------------------------------------

---
imagePullSecret:
  registry: "{{ inv_op_stack.private_registry.registry_full_url | default(software.addon_cividash.cividash.registry) }}"
  username: "{{ inv_k8s.gitlab_access.user }}"
  password: "{{ inv_k8s.gitlab_access.token }}"
  email: "{{ inv_k8s.gitlab_access.user_email }}"

cividash:
  image:
    name: "{{ inv_op_stack.private_registry.registry_full_url | default(software.addon_cividash.cividash.registry) }}/{{ software.addon_cividash.cividash.repository }}"
    tag: "{{ software.addon_cividash.cividash.tag }}"
